// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATK17vsxm-Kh4VsYhtpzBh1VKzeItALCc',
    appId: '1:825554932672:web:378b0acbdab3250b0d2e25',
    messagingSenderId: '825554932672',
    projectId: 'yaredubal',
    authDomain: 'yaredubal.firebaseapp.com',
    storageBucket: 'yaredubal.firebasestorage.app',
    measurementId: 'G-EC6G24R37C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuezST6PsIHsTzCA4dLUml3yofQtgM46Q',
    appId: '1:825554932672:android:edc5557021a5d8eb0d2e25',
    messagingSenderId: '825554932672',
    projectId: 'yaredubal',
    storageBucket: 'yaredubal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXCDCl30iG8cVc9NRZl5c4poDWc1opLoM',
    appId: '1:825554932672:ios:12cd487f4faa60070d2e25',
    messagingSenderId: '825554932672',
    projectId: 'yaredubal',
    storageBucket: 'yaredubal.firebasestorage.app',
    iosBundleId: 'com.example.yaredubal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXCDCl30iG8cVc9NRZl5c4poDWc1opLoM',
    appId: '1:825554932672:ios:12cd487f4faa60070d2e25',
    messagingSenderId: '825554932672',
    projectId: 'yaredubal',
    storageBucket: 'yaredubal.firebasestorage.app',
    iosBundleId: 'com.example.yaredubal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATK17vsxm-Kh4VsYhtpzBh1VKzeItALCc',
    appId: '1:825554932672:web:954fee60d2c271a90d2e25',
    messagingSenderId: '825554932672',
    projectId: 'yaredubal',
    authDomain: 'yaredubal.firebaseapp.com',
    storageBucket: 'yaredubal.firebasestorage.app',
    measurementId: 'G-VNBJYYCTKK',
  );

}